import { createClient } from '@insforge/sdk';

/**
 * InsForge BaaS Client Configuration
 *
 * Connected Project: jyotish-ai
 * API Base URL: https://c95v9mim.ap-southeast.insforge.app
 */
const INSFORGE_URL =
  process.env.EXPO_PUBLIC_INSFORGE_URL ||
  'https://c95v9mim.ap-southeast.insforge.app';

const INSFORGE_ANON_KEY =
  process.env.EXPO_PUBLIC_INSFORGE_ANON_KEY ||
  'anon_61a8c114d82b73f0652bf1898202bcbddeb5c8c91587a5531ea93b5ec8e85d63';

export const insforge = createClient({
  baseUrl: INSFORGE_URL,
  anonKey: INSFORGE_ANON_KEY,
});

export interface LivePanchangResponse {
  date: string;
  day: string;
  sunrise: string;
  sunset: string;
  tithi: {
    name: string;
    paksha: string;
    end_time: string;
  };
  nakshatra: {
    name: string;
    lord: string;
    end_time: string;
  };
  yoga: {
    name: string;
    end_time: string;
  };
  karana: {
    name: string;
    end_time: string;
  };
  rahu_kaal: string;
  abhijit_muhurat: string;
  brahma_muhurat: string;
  auspicious_recommendation: string;
}

export interface AstrologerResponse {
  reply: string;
  sessionId?: string;
  recommendedTopics?: string[];
  remedyHighlight?: string;
}

export interface AuthUser {
  id: string; // Unique user identifier (UUID) generated by InsForge backend
  email: string;
  name?: string;
  emailVerified?: boolean;
  createdAt?: string;
}

export interface UserSyncPayload {
  userName: string;
  punyaPoints: number;
  streak: number;
  jaapTotal: number;
  favorites: string[];
  language: string;
  adsRemoved?: boolean;
  userId?: string;
}

/**
 * InsForge Backend Service Utilities
 */
export const InsForgeService = {
  /**
   * Register a new unique user with InsForge BaaS.
   */
  async signUp(params: {
    email: string;
    password: string;
    name?: string;
  }): Promise<{ user: AuthUser | null; error: string | null; accessToken?: string }> {
    try {
      const res = await insforge.auth.signUp({
        email: params.email.trim(),
        password: params.password,
        name: params.name?.trim(),
      });

      if (res.error) {
        return { user: null, error: res.error.message || 'Failed to create account.' };
      }

      if (res.data && res.data.user) {
        const u = res.data.user;
        const userName = u.profile?.name || (u.metadata?.name as string | undefined) || undefined;
        return {
          user: {
            id: u.id,
            email: u.email,
            name: userName,
            emailVerified: u.emailVerified,
            createdAt: u.createdAt,
          },
          error: null,
          accessToken: res.data.accessToken || undefined,
        };
      }

      return { user: null, error: 'No user data returned from server.' };
    } catch (err: any) {
      return { user: null, error: err?.message || 'Network error during signup.' };
    }
  },

  /**
   * Authenticate an existing user with email and password on InsForge.
   */
  async signIn(params: {
    email: string;
    password: string;
  }): Promise<{ user: AuthUser | null; error: string | null; accessToken?: string }> {
    try {
      const res = await insforge.auth.signInWithPassword({
        email: params.email.trim(),
        password: params.password,
      });

      if (res.error) {
        return { user: null, error: res.error.message || 'Invalid email or password.' };
      }

      if (res.data && res.data.user) {
        const u = res.data.user;
        const userName = u.profile?.name || (u.metadata?.name as string | undefined) || undefined;
        return {
          user: {
            id: u.id,
            email: u.email,
            name: userName,
            emailVerified: u.emailVerified,
            createdAt: u.createdAt,
          },
          error: null,
          accessToken: res.data.accessToken || undefined,
        };
      }

      return { user: null, error: 'No user session returned from server.' };
    } catch (err: any) {
      return { user: null, error: err?.message || 'Network error during sign in.' };
    }
  },

  /**
   * Sign out the active user session on InsForge.
   */
  async signOut(): Promise<{ error: string | null }> {
    try {
      const res = await insforge.auth.signOut();
      return { error: res.error ? res.error.message : null };
    } catch (err: any) {
      return { error: err?.message || 'Sign out error.' };
    }
  },

  /**
   * Retrieve the currently authenticated user from InsForge SDK token manager / session.
   */
  async getCurrentUser(): Promise<AuthUser | null> {
    try {
      const res = await insforge.auth.getCurrentUser();
      if (res.data?.user) {
        const u = res.data.user;
        const userName = u.profile?.name || (u.metadata?.name as string | undefined) || undefined;
        return {
          id: u.id,
          email: u.email,
          name: userName,
          emailVerified: u.emailVerified,
          createdAt: u.createdAt,
        };
      }
      return null;
    } catch {
      return null;
    }
  },

  /**
   * Health check to confirm live connectivity to the InsForge backend.
   */
  async checkHealth(): Promise<{ ok: boolean; url: string }> {
    try {
      const { data, error } = await insforge.functions.invoke('panchang-daily', {
        method: 'GET',
      });
      return { ok: !error && !!data, url: INSFORGE_URL };
    } catch {
      return { ok: false, url: INSFORGE_URL };
    }
  },

  /**
   * Fetch live daily Vedic Panchang from the InsForge backend edge function.
   */
  async getLivePanchang(): Promise<LivePanchangResponse | null> {
    try {
      const { data, error } = await insforge.functions.invoke('panchang-daily', {
        method: 'GET',
      });
      if (error || !data) {
        return null;
      }
      return data as LivePanchangResponse;
    } catch (e) {
      console.warn('[InsForge] Failed to fetch live panchang:', e);
      return null;
    }
  },

  /**
   * Ask the Vedic Astrologer AI via the InsForge edge function.
   */
  async askAstrologer(message: string, sessionId?: string): Promise<AstrologerResponse | null> {
    try {
      const { data, error } = await insforge.functions.invoke('gemini-astrologer', {
        body: { message, session_id: sessionId },
      });
      if (error || !data) {
        return null;
      }
      const raw = data as Record<string, any>;
      return {
        reply: raw.reply || '',
        sessionId: raw.session_id,
        recommendedTopics: raw.recommended_topics,
        remedyHighlight: raw.vedic_remedy_highlight,
      };
    } catch (e) {
      console.warn('[InsForge] Astrologer invocation error:', e);
      return null;
    }
  },

  /**
   * Sync user devotion stats & favorites with the InsForge database.
   * Attaches the unique user ID when authenticated.
   */
  async syncUserData(payload: UserSyncPayload): Promise<{ ok: boolean }> {
    try {
      const row: Record<string, any> = {
        user_name: payload.userName || 'Bhakt',
        punya_points: payload.punyaPoints,
        streak: payload.streak,
        jaap_total: payload.jaapTotal,
        favorites: payload.favorites,
        language: payload.language,
        ads_removed: !!payload.adsRemoved,
        updated_at: new Date().toISOString(),
      };

      if (payload.userId) {
        row.user_id = payload.userId;
      }

      const { error } = await insforge.database
        .from('bhakti_user_stats')
        .insert([row]);

      if (error) {
        console.warn('[InsForge] Cloud sync notice:', error.message);
      }
      return { ok: !error };
    } catch {
      return { ok: false };
    }
  },

  /**
   * Generate authentic Vedic recitation audio via the secure ElevenLabs InsForge Edge Function.
   */
  async generateTtsAudio(params: {
    text: string;
    voiceId?: string;
  }): Promise<{ audioBase64: string | null; error: string | null }> {
    try {
      const { data, error } = await insforge.functions.invoke('elevenlabs-tts', {
        body: {
          text: params.text,
          voice_id: params.voiceId || 'pNInz6obpgDQGcFmaJgB', // Adam / Vedic tone
        },
      });

      if (error || !data) {
        return {
          audioBase64: null,
          error: error?.message || 'Failed to synthesize audio from InsForge',
        };
      }

      const res = data as { audioBase64?: string; error?: string; format?: string };
      if (res.error) {
        return { audioBase64: null, error: res.error };
      }

      return { audioBase64: res.audioBase64 || null, error: null };
    } catch (err: any) {
      return {
        audioBase64: null,
        error: err?.message || 'Network error during audio synthesis',
      };
    }
  },
};

